"""add_parent_task_id

Revision ID: 56dc10225885
Revises: 07c545e61b04
Create Date: 2026-05-25 12:18:30.917825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56dc10225885'
down_revision: Union[str, None] = '07c545e61b04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('parent_task_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_tasks_parent_task_id'), 'tasks', ['parent_task_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'tasks', ['parent_task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_parent_task_id'), table_name='tasks')
    op.drop_column('tasks', 'parent_task_id')
    # ### end Alembic commands ###
