"""add_pinned_messages

Revision ID: 5e6f29c84a9f
Revises: 08f9dd3a32d8
Create Date: 2026-05-25 14:55:57.242752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e6f29c84a9f'
down_revision: Union[str, None] = '08f9dd3a32d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pinned_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('pinned_by', sa.UUID(), nullable=False),
    sa.Column('pinned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pinned_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'message_id', name='uq_pinned_message')
    )
    op.create_index(op.f('ix_pinned_messages_channel_id'), 'pinned_messages', ['channel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pinned_messages_channel_id'), table_name='pinned_messages')
    op.drop_table('pinned_messages')
    # ### end Alembic commands ###
